DROP TABLE `language_text`;
INSERT INTO `config` (`name`, `value`) VALUES ('test_sql_update','1');

# Integrate template editor from supungs GSoC 2013
INSERT INTO `privileges` (`privilege_id`, `title_var`, `description`, `create_date`, `link`, `menu_sequence`, `open_to_public`) VALUES (11, 'template_editor', 'Template Editor', NOW(), 'template_editor/index.php', 110, 0);

INSERT INTO `user_group_privilege` (`user_group_id`, `privilege_id`, `user_requirement`) VALUES (1, 11, 0);


/*
## Language for template editor
INSERT INTO `language_text` VALUES ('en', '_template', 'template_editor', 'Template Editor', '2013-07-13 08:46:35', ''),
('en', '_template', 'create_template', 'Create Template', '2013-07-13 08:46:35', ''),
('en', '_template', 'pages', 'Pages', '2013-07-13 08:46:35', ''),
('en', '_template', 'edit_structure', 'Edit Structure', '2013-07-13 08:46:35', ''),
('en', '_template', 'edit_layout', 'Edit Theme', '2013-07-13 08:46:35', ''),
('en', '_template', 'edit_page', 'Edit Page', '2013-07-13 08:46:35', ''),
('en', '_template', 'edit_template', 'Edit Template', '2013-07-13 08:49:45', ''),
('en', '_template', 'edit_metadata', 'Edit Metadata', '2013-07-13 08:49:45', ''),
('en', '_template', 'min', 'Min', '2013-07-13 08:49:45', ''),
('en', '_template', 'max', 'Max', '2013-07-13 08:52:00', ''),
('en', '_template', 'undo', 'Undo', '2013-07-13 08:52:00', ''),
('en', '_template', 'redo', 'Redo', '2013-07-13 08:52:00', ''),
('en', '_template', 'add_page_templates', 'Add Page Templates', '2013-07-13 08:53:00', ''),
('en', '_template', 'add_page_template', 'Add Page Template', '2013-07-13 08:53:00', ''),
('en', '_template', 'add_tests', 'Add Tests', '2013-07-13 08:55:00', ''),
('en', '_template', 'add_test', 'Add Test$AB(', '2013-07-13 08:55:00', ''),
('en', '_template', 'add_forum', 'Add Forum', '2013-07-13 08:55:00', ''),
('en', '_template', 'move_up', 'Move Up', '2013-07-13 08:57:00', ''),
('en', '_template', 'move_down', 'Move Down', '2013-07-13 08:57:00', ''),
('en', '_template', 'page_templates_tag', 'Page Templates', '2013-07-13 08:59:00', ''),
('en', '_template', 'page_template_tag', 'Page Template', '2013-07-13 08:59:00', ''),
('en', '_template', 'test', 'Test', '2013-07-13 08:59:00', ''),
('en', '_template', 'forum', 'Forum', '2013-07-13 08:59:00', ''),
('en', '_template', 'invalid_xml', 'There is a syntax error in the xml code.', '2013-07-13 09:01:00', ''),
('en', '_template', 'template_name', 'Template Name', '2013-07-13 09:06:00', ''),
('en', '_template', 'template_type', 'Template Type', '2013-07-13 09:06:00', ''),
('en', '_template', 'template_description', 'Template Description', '2013-07-13 09:06:00', ''),
('en', '_template', 'template_license', 'Template License', '2013-07-13 09:06:00', ''),
('en', '_template', 'template_url', 'Template URL', '2013-07-13 09:08:00', ''),
('en', '_template', 'maintainer_name', 'Maintainer Name', '2013-07-13 09:08:00', ''),
('en', '_template', 'maintainer_email', 'Maintainer Email', '2013-07-13 09:08:00', ''),
('en', '_template', 'release_version', 'Release Version', '2013-07-13 09:09:00', ''),
('en', '_template', 'release_date', 'Release Date', '2013-07-13 09:09:00', ''),
('en', '_template', 'release_state', 'Release State', '2013-07-13 09:09:00', ''),
('en', '_template', 'release_note', 'Release Note', '2013-07-13 09:09:00', ''),
('en', '_template', 'empty_fields_error', 'One or more required fields are empty.', '2013-07-13 09:09:00', ''),
('en', '_template', 'confirm_template_delete', 'Are you sure you want to delete the template <strong>%s</strong>?', '2013-07-13 09:15:00', '');
INSERT INTO `language_text` VALUES ('en', '_template', 'delete_template', 'Delete Template', '2013-07-13 08:49:45', ''),
('en', '_template', 'confirm_template_delete', 'Are you sure you want to delete the template <strong>%s</strong>?', '2013-07-13 09:15:00', ''),
('en', '_template', 'bold', 'Bold', '2013-08-10 09:40:00', ''),
('en', '_template', 'italic', 'Italic', '2013-08-10 09:40:00', ''),
('en', '_template', 'underline', 'Underline', '2013-08-10 09:40:00', ''),
('en', '_template', 'align_left', 'Align Left', '2013-08-10 09:40:00', ''),
('en', '_template', 'align_right', 'Align Right', '2013-08-10 09:40:00', ''),
('en', '_template', 'align_center', 'Align Center', '2013-08-10 09:40:00', ''),
('en', '_template', 'justify', 'Justify', '2013-08-10 09:40:00', ''),
('en', '_template', 'font_family', 'Font Family', '2013-08-10 09:40:00', ''),
('en', '_template', 'font_size', 'Font Size', '2013-08-10 09:40:00', ''),
('en', '_template', 'font_color', 'Font Color', '2013-08-10 09:40:00', ''),
('en', '_template', 'background-color', 'Background Color', '2013-08-10 09:40:00', ''),
('en', '_template', 'background-image', 'Background Image', '2013-08-10 09:40:00', ''),
('en', '_template', 'border-width', 'Border Width', '2013-08-10 09:40:00', ''),
('en', '_template', 'border-style', 'Border Style', '2013-08-10 09:40:00', ''),
('en', '_template', 'border-color', 'Border Color', '2013-08-10 09:40:00', ''),
('en', '_template', 'confirm_image_delete', 'Are you sure you want to delete <strong>%s</strong>?', '2013-08-10 09:40:00', ''),
('en', '_template', 'selector', 'Selector', '2013-08-19 09:40:00', ''),
('en', '_template', 'edit_mode ', 'Edit Mode', '2013-08-19 09:40:00', ''),
('en', '_template', 'basic', 'Basic', '2013-08-19 09:40:00', ''),
('en', '_template', 'advanced', 'Advanced', '2013-08-19 09:40:00', ''),
('en', '_template', 'property', 'Property', '2013-08-19 09:40:00', ''),
('en', '_template', 'value', 'Value', '2013-08-19 09:40:00', ''),
('en', '_template', 'associated_images ', 'Associated Images ', '2013-08-19 09:40:00', ''),
('en', '_template', 'screenshot', 'Screenshot', '2013-08-19 09:40:00', ''),
('en', '_template', 'delete_image', 'Delete Image', '2013-08-19 09:40:00', ''),
('en', '_template', 'ordered_list', 'Ordered List', '2013-09-08 09:40:00', ''),
('en', '_template', 'image', 'Image', '2013-09-08 09:40:00', ''),
('en', '_template', 'table', 'Table', '2013-09-08 09:40:00', ''),
('en', '_template', 'format', 'Format', '2013-09-08 09:40:00', ''),
('en', '_template', 'rows', 'Rows', '2013-09-08 09:40:00', ''),
('en', '_template', 'columns', 'Columns', '2013-09-08 09:40:00', ''),
('en', '_template', 'auto_generate', 'Auto Generate', '2013-09-08 09:40:00', ''),
('en', '_template', 'number_of_rows', 'Rows', '2013-09-08 09:40:00', ''),
('en', '_template', 'number_of_columns', 'Columns', '2013-09-08 09:40:00', ''),
('en', '_template', 'link', 'Link', '2013-09-08 09:40:00', ''),
('en', '_template', 'paragraph', 'Paragraph', '2013-09-08 09:40:00', ''),
('en', '_msgs', 'TR_HELP_TEMPLATE_EDITOR', '<h2>Template Editor</h2><p>Template Editor allows administrators to create, edit and manage AContent templates easily. Template Editor has four tabs and the first tab is for creating new templates. The other three shows existing templates of theme, structure and page templates and you can edit any of the existing templates by clicking on them</p><h3>Creating a New Template</h3><p>To create a new template you have to provide the details about template. Template Name, Template Type, Maintainer Name, Release Version and Release State fields are required. Most fields are self-explanatory. You can choose the template type out of the three types: Theme, Page and Structure. By clicking the Create button the new template will be created and opened in the respective template editor according to the type.</p>', '2013-09-18 09:40:00', ''),
('en', '_msgs', 'TR_HELP_STRUCTURE_EDITOR', '<h2>Structure Template Editor</h2><p>User interface of the structure template editor has a text field, a tree view and a toolbar. The text field display the XML script. that define the template and the treeview shows the template as a tree like structure. You can easily manipulate the tree view using the toolbar and mouse by dragging nodes.</p><h3>Toolbar</h3><p>You can click and select nodes of the treeview and availability of toolbar buttons change according to the selected node.</p><ul><li><img src=\"../images/add_sub_folder.gif\" alt=\"\" /> Inserts a sub folder under the currently selected node. Only available for structure or folder nodes.<li><img src=\"../images/add_sub_page.gif\" alt=\"\" /> Inserts a page under the currently selected node. Only available for structure and folder nodes.<li><img src=\"../images/tree/tree_page_templates.gif\" alt=\"\" /> Inserts a pagetemplates node under the currently selected page. <li><img src=\"../images/tree/tree_page_template.gif\" alt=\"\" /> Inserts a page template node under the currently selected page templates node.<li><img src=\"../images/tree/tree_tests.gif\" alt=\"\" /> Inserts a tests node under the currently selected page.<li><img src=\"../images/tree/tree_test.gif\" alt=\"\" /> Inserts a test node under the currently tests node.<li><img src=\"../images/tree/tree_forum.gif\" alt=\"\" /> Inserts a forum under the currently selected page.<li>Use the Name field set the name of the currently selected node. Only available for structure, folder, page, test, page template and forum nodes.<li>Use the Min and Max fields to set the minimum and maximum numbers for the currently selected node. Only available for structure, folder, page, test, page template and forum nodes.<li><img src=\"../images/x.gif\" alt=\"\" /> Delete the currently selected node. Deleting the top structure element will delete the whole template.<li><img src=\"../images/move_up.png\" alt=\"\" /><img src=\"../images/move_down.png\" alt=\"\" /> Move up/down the currently selected node.</ul><p>You can easily reorder tree nodes by dragging and you can drop them only within a suitable parent node. As an example you can move a Test node only to directly under a Page node. You can also modify the XML code in the text field and the treeview will be auto updated to reflect the changes.</p>', '2013-09-18 09:40:00', ''),
('en', '_msgs', 'TR_HELP_LAYOUT_EDITOR', "<h2>Theme Template Editor</h2><p>Theme template editor allows you to edit themes/layout templates easily without coding any CSS. This has to modes: basic and advanced. In basic mode you can modify the template entirely using the user interface and in advanced mode you can directly edit the CSS script of the template.</p><p>Theme template editor has preview panel to display a live preview of the template. In basic mode you can select the elements in the preview panel and the CSS properties of the selected element will be displayed on the left side panel. Using this panel you can easily set values for some basic properties such as text alignment, font, background and border. It also provide the option to add any other CSS property and value pair. All the non basic properties currently defined for the selected item are also displayed and their values can be edited easily. In the advanced mode CSS code is displayed and you can directly edit it. All the changes will be reflected in the preview panel instantly.</p><p>There a seperat panel at the bottom to manage images associated with the theme. Using this panel you can upload new images to be used with the template and delete existing images. There's another panel to upload the screenshot image for the template.</p>", '2013-09-18 09:40:00', ''),
('en', '_msgs', 'TR_HELP_PAGE_TEMPLATE_EDITOR', '<h2>Page Template Editor</h2><p>Page template editor allows you to edit page templates easily without coding any HTML. This also has to modes: basic and advanced. </p><p>In basic mode you have a WYSIWYG editor and you can insert some basic page elements such as paragraph, list and image using the toolbar. It also provide functionality to modify text alignment, change text format, font etc. In advanced mode you get the HTML code and it can be directly edited. A page template should only define the structure of a page. So focus on the elements in the page rather than the content and be careful not to put unnecessary content when creating a page template.</p><p>At the bottom there is a panel to upload a screenshot image for the template. Or you can use the sreenshot auto generate feature to quickly generate a screenshot automatically.</p>', '2013-09-18 09:40:00', '');
*/