ALTER TABLE primary_resources ENGINE = MYISAM DEFAULT CHARSET=utf8;
ALTER TABLE primary_resources_types ENGINE = MYISAM DEFAULT CHARSET=utf8;
ALTER TABLE resource_types ENGINE = MYISAM DEFAULT CHARSET=utf8;
ALTER TABLE secondary_resources ENGINE = MYISAM DEFAULT CHARSET=utf8;
ALTER TABLE secondary_resources_types ENGINE = MYISAM DEFAULT CHARSET=utf8;