<?php 
/************************************************************************/
/* AFrame                                                               */
/************************************************************************/
/* Copyright (c) 2009                                                   */
/* Adaptive Technology Resource Centre / University of Toronto          */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the AFrame 0.1 installation script.       */
/* File generated 2009-10-07 09:10:45                                   */
/************************************************************************/
/************************************************************************/
/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  '');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'aframe');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: AF_                                                 */
define('TABLE_PREFIX',                 'AF_');

/* Where the temporary files are located.  This includes all file       */
/* manager and imported files.  If security is a concern, it is         */
/* recommended that the temporary directory be moved outside of the web	*/
/* accessible area.														*/
define('AF_TEMP_DIR', 'C:\\Development\\aframe\\temp\\');

/* DO NOT ALTER THIS LAST LINE                                          */
define('AF_INSTALL', TRUE);

?>