INSERT INTO `TR_language_text` VALUES ('en', '_template','is_author','I would like to author content.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','organization','Organization',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','phone','Phone',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','address','Street Address',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','city','City',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','province','Province/State/Region',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','country','Country',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','postal_code','Postal Code',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','getting_start','Getting Start',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','getting_start_info','<span style="font-weight:bold">Transformable</span> is a learning object repository that supports complete customization of the learning content to the individual needs of each learner.<br /><br /><span style="font-weight:bold">To search the repository</span>, type keywords into the field below, or click the "Advanced Search" link for advanced search capabilities.<br /><br /><span style="font-weight:bold">To create your own account</span>, click the Register link at the top left corner. While you do not need an account to search the repository and view the content, an account allows you to save your preferences and other settings.<br /><br /><span style="font-weight:bold">To contribute learning resource</span>, you must create an account with Authoring privileges or modify your existing account to gain Authoring privileges. ',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','search','Search',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','create_course','Create Course',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','search_and_add','Please search and add courses',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','course_wizard','"Create Course" Wizard',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','create_course_1','<span style="font-weight:bold">Method 1</span>: Create a course by using',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','create_course_2','<span style="font-weight:bold">Method 2</span>: Import a content package. Or, if you have the Web address directly to a content package, enter it into the URL field to import it directly from the Web.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','upload_content_package','Upload a Content Package or Common Cartridge',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','specify_url_to_content_package','Or, Specify a URL to a Content Package or Common Cartridge',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','hide_course','Hide the course from other users',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','upload_progress','Upload Progress',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','close','Close',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','window_auto_close','This window will close automatically.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','my_courses','My courses',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','my_authoring_course','My authoring course',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','remove_from_list','Remove from "My Courses"',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','add_into_list','Add into "My courses"',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','export','Export',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','items','Items',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','of','of',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','results','Results',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','prev','Prev',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','next','Next',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','authoring_img_info','indicates my own authoring course.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','page_info','Last Modified: %s.  Revision: %s.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template','page_info_date_format','%l %M %j, %Y - %H:%i',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_apr', 'Apr', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_april', 'April', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_aug', 'Aug', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_august', 'August', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_created', 'Date Created', now(), 'view profile');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_dec', 'Dec', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_december', 'December', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_feb', 'Feb', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_february', 'February', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_fri', 'Fri', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_friday', 'Friday', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_jan', 'Jan', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_january', 'January', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_jul', 'Jul', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_july', 'July', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_jun', 'Jun', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_june', 'June', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_mar', 'Mar', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_march', 'March', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_may', 'May', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_may_short', 'May', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_mon', 'Mon', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_monday', 'Monday', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_nov', 'Nov', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_november', 'November', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_oct', 'Oct', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_october', 'October', now(), 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_of_birth', 'Date of birth', '2004-06-24 12:31:02', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_sat', 'Sat', '2003-05-20 12:26:55', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_saturday', 'Saturday', '2003-05-20 12:24:48', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_sep', 'Sep', '2003-05-20 12:33:42', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_september', 'September', '2003-05-20 12:29:44', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_sun', 'Sun', '2003-05-20 12:26:09', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_sunday', 'Sunday', '2003-05-20 12:23:52', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_taken', 'Date Taken', '2003-05-19 17:46:06', 'My Tests');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_thu', 'Thu', '2003-05-20 12:26:40', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_thursday', 'Thursday', '2003-05-20 12:24:32', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_tue', 'Tue', '2003-05-20 12:26:24', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_tuesday', 'Tuesday', '2003-05-20 12:24:12', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_wed', 'Wed', '2003-05-20 12:26:32', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'date_wednesday', 'Wednesday', '2003-05-20 12:24:21', 'date');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'goto_top', 'Go to Top', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'content_navigation', 'Content Navigation', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'hide', 'Hide', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'show', 'Show', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'export_content', 'Export Content', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'edit_this_page', 'Edit This Page', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_top_folder', 'Add Top Folder', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_sibling_folder', 'Add Sibling Folder', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_top_page', 'Add Top Page', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_sibling_page', 'Add Sibling Page', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_this_page', 'Delete This Page', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'enter_edit_mode', 'Enter Edit Mode', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'exit_edit_mode', 'Exit Edit Mode', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_content', 'Delete Content', '2003-05-20 12:26:32', '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'outline', 'Outline', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'translate_to', 'Translate To:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'expand', 'Expand', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'collapse', 'Collapse', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_property', 'Course Property', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'del_course', 'Delete This Course', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'exit_course', 'Exit Course', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'shortcuts', 'Shortcuts', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_copyright', 'Optional Copyright Notice', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'primary_language', 'Primary Language', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'manage_tests', 'Manage Tests/Surveys', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_test', 'Create Test/Survey', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'import_test', 'Import Test', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'question_database', 'Question Database', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'question_categories', 'Question Categories', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_category', 'Delete Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'edit_test', 'Edit Test/Survey', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'preview_questions', 'Preview Questions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'preview', 'Preview', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'submissions', 'Submissions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_test', 'Delete Test/Survey', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_new_question', 'Create New Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'edit_question', 'Edit Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete', 'Delete', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'my_tests', 'My Tests', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'user_requirement', 'User Requirement', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'must_be_author', 'Must be an author', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'must_be_author_of_course', 'Must be an author of the current course', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'must_in_course', 'Must be in a course', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'none', 'None', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'import_test', 'Import Test', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'upload_test', 'Select Test Package to Upload', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'availability', 'Availability', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'result_release', 'Release Results', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'assigned_to', 'Assigned To', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'questions', 'Questions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'statistics', 'Statistics', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'ongoing', 'On Going!', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'expired', 'Expired', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'pending', 'Pending', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'startend_date_format', '%%j/%%n/%%y %%G:%%i', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'to_2', 'to', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'release_immediate', 'Once quiz has been submitted', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'release_marked', 'Once quiz has been submitted and all questions have been marked', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'release_never', 'Do not release results', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'unmarked', 'Unmarked', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'everyone', 'Everyone', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'num_questions_per_test', 'questions per test.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_description', 'Test Description', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'num_takes_test', 'Attempts Allowed', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'unlimited', 'Unlimited', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'display', 'Display', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'all_questions_on_page', 'All questions on one page', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'one_question_per_page', 'One question per page', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'pass_score', 'Pass Score', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'no_pass_score', 'No pass score', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'percentage_score', 'percentage score', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'points_score', 'points score', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'pass_feedback', 'Pass Feedback', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'fail_feedback', 'Fail Feedback', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'randomize_questions', 'Randomize Questions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'instructions', 'Instructions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'category_id', 'Category ID', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'manage_category', 'Manage Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_category', 'Create Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'import_question', 'Import Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'upload_question', 'Upload Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'cats_all', 'All Categories', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'cats_uncategorized', 'Uncategorized', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'question', 'Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_to_test_survey', 'Add to Test/Survey', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create', 'Create', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_lk', 'Likert', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_ma', 'Multiple Answer', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_matching', 'Matching (Simple)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_matchingdd', 'Matching (Graphical)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_mc', 'Multiple Choice', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_open', 'Open Ended', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_ordering', 'Ordering', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'test_tf', 'True or False', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'category', 'Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'type', 'Type', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'choice', 'Choice', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'preset_scales', 'Preset &amp; Previously Used Scales', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'presets', 'Presets', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'prev_used', 'Previously Used', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'set_preset', 'Apply Preset', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'use_visual_editor', '<small style="text-decoration:underline;">(Editor)</small>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_always', 'Always', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_disagree', 'Disagree', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_excellent', 'Excellent', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_fair', 'Fair', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_good', 'Good', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_important', 'Important', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_little_importance', 'Of Little Importance', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_mod_important', 'Moderately Important', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_never', 'Never', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_occasionally', 'Occasionally', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_poor', 'Poor', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_rarely', 'Rarely', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_strongly_agree', 'Strongly Agree', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_strongly_disagree', 'Strongly Disagree', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_undecided', 'Undecided', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_unimportant', 'Unimportant', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_very_frequently', 'Very Frequently', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_very_good', 'Very Good', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_very_important', 'Very Important', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_very_poor', 'Very Poor', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_very_rarely', 'Very Rarely', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'paste', 'Paste', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'lk_agree', 'Agree', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'leave_blank', 'Leave blank', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'back', 'Back', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'answers', 'Answers', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'answer', 'Answer', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'a', 'A', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'b', 'B', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'c', 'C', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'd', 'D', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'e', 'E', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'f', 'F', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'g', 'G', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'h', 'H', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'i', 'I', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'j', 'J', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'optional_feedback', 'Optional Feedback', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'answer_size', 'Answer Size', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'one_word', 'One Word', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'one_sentence', 'One Sentence', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'short_paragraph', 'Short Paragraph', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'one_page', 'One Page', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'correct_answer', 'Correct Answer', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'item', 'Item', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'statement', 'Statement', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'true', 'True', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'false', 'False', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'close_window', 'Close Window', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'form_editor', 'Form Editor', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'num', 'No.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'points', 'Points', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'order', 'Order', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'questions_for', 'Questions for', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_questions', 'Add Questions', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'remove_question', 'Remove Question', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'update', 'Update', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'file_manager', 'File Manager', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'current_path', 'Path to Current Directory:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'home', 'Home', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_file_folder', 'Add File or Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_folder_here', 'To create a folder, enter name here:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'keep_it_short', 'Tip: Keep it short, no spaces.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_folder', 'Create Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'depth_reached', 'Directory depth limit has been reached.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'enable_uploader', 'Enable multi-file uploader tool', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'file_manager_new', 'Create a New File', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'upload_files', 'Upload files', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'size', 'Size', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'file_placeholder', 'File Name Placeholder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'kb', '<acronym title="Kilobytes">KB</acronym>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'remove_queued_file', 'Remove file from queue', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'click_browse_files', 'Click <em>Browse Files</em> to add files to the queue', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'total', 'Total', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'browse_files', 'Browse Files', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'rename', 'Rename', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'move', 'Move', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'directory_total', 'Directory Total', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_total', 'Course Total', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_available', 'Course Available', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'bt', '<acronym title="Byte">B</acronym>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'mb', '<acronym title="Megabyte">MB</acronym>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'create_new_file', 'Create New File', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'plain_text', 'Plain Text', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'html', 'HTML', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'body', 'Body', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'extract_archive', 'Extract Archive', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'use_as_alternative', 'Use As Alternative', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'file_manager_frame', 'File Manager Frame', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'frame_contains', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'return_file_manager', 'Return to the File Manager', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'download_file', 'Download File', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'remove_frame', 'Remove Frame', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'filemanager_date_format', '%Y-%m-%d %H:%i', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'new_name', 'New Name', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'current_location', '(Current location)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'select_directory', 'Please choose the folder you want to move the selected files to:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'zip_archive', 'Zip Archive', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'zip_illegal_contents', 'The contents of this archive are listed below. Illegal file types will not be extracted, and file names containing illegal characters will be translated.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'extract_tip', 'Tip: Use an empty directory name to extract the contents into the current directory.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'extract', 'Extract', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'folder', 'Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'illegal_file', 'Illegal File Type', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'archive_total', 'Archive Total', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_available_zip1', 'Course Available (before extraction)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_available_zip2', 'Course Available (after extraction)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'directory_name', 'Directory Name', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_total_zip', 'Course Total (before extraction)', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'zip_file_manager', 'Zip File Manager', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'insert', 'Insert', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'close_file_manager', 'Close File Manager', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'alternate_text', 'Alternate Text', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_categories', 'Course Categories', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'inline_editor_tip', 'Tip: click to edit the editable fields.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'category_id', 'Category ID', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'category_name', 'Category Name', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_course_category', 'Add Course Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'user_table_summary', 'Edit, change passwords, or delete users', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'course_category_table_summary', 'Edit or delete course categories', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_course_category', 'Delete Course Category', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_CHECKBOX_STATUS','Invalid checkbox status.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_NO_PRIV','User has no privilege to do this action.',now(),'');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_IMPORTDIR_IMS_NOTVALID','The file does not appear to be a valid ZIP file.','2005-06-27 11:37:47','IMS file is not a ZIP file.');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_MAX_SIZE','The file exceeded the maximum allowable size limit of %s.','2004-05-06 13:18:19','');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_NOT_SELECTED','You did not select a file to upload.','2003-05-16 13:42:17','error msg');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_IMPORTFILE_EMPTY','The import file must not be empty.','2003-05-16 13:42:17','error msg');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_IMPORTDIR_FAILED','Unable to create import directory.','2005-07-20 14:02:57','error msg');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_IMPORT_FAILED','Import Failed','2005-01-15 09:50:40','');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_NO_SEARCH_TEXT','Please provide search text.','2005-01-15 09:50:40','');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_NO_CONTENT_SPACE', 'Not enough space to import content directory. %s KB over the limit.', now(), 'error msg');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_IMPORT_CARTRIDGE_FAILED', 'Import failed. Does not appear to be a valid content package or common cartridge.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_MISSING_COURSE_ID', 'Please select a course.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_EXPORT_CANCELLED', 'Export cancelled successfully.', now(), 'feedback msg');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_UNABLE_UPDATE_DB', 'Unable to update DB.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_COURSE_1', 'Are you sure you want to <strong>Delete</strong> the course <strong><em>%s</em></strong>?', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_COURSE_2', 'Are you <strong>really really</strong> sure you want to <b>Delete</b> the course <strong><em>%s</em></strong>? Deleted courses can not be recovered.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_KEYWORDS', 'Empty keywords', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_WEB_SERVICE_ID', 'Empty web service ID', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_WEB_SERVICE_ID', 'Invalid web service ID', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_CONNECT_SERVER', 'Failed to connect to server: %s', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_NO_QUESTION_CATS', 'No Categories.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_TEST_CATEGORY', 'Are you sure you want to delete test category <strong>%s</strong>?', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_QUESTION_DELETED', 'Question was successfully deleted.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE', 'Are you sure you want to delete these items?<br />\r\n\r\n <ul> %s </ul>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_IMPORT_SUCCEEDED', 'Import was successful.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_QTI_WRONG_PACKAGE', 'Import failed.  Please note that Transformable only supports QTI 1.2.1 import.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_TEST', 'Are you sure you want to delete the test/survey <strong><em>%s</em></strong>? The questions, however, will not be deleted.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_ADD_TEST_QUESTIONS', 'Are you sure you want to <em>add</em> the following questions? \r\n<ul>%s</ul>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_NO_QUESTIONS_SELECTED', 'You did not select any questions to add to this test.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_WARNING_QUESTION_WEIGHT', 'One or more of the questions on this test do not have points associated with them.  Ensure that this is correct, or enter values for questions that do not have points.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_QUESTION_REMOVED', 'Question was successfully removed from test/survey.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_REMOVE_TEST_QUESTION', 'Are you sure you want to remove this question from this test? Removing the question will not delete it from the question database.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_QUESTION_UPDATED', 'Question was successfully updated.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_ITEM_NOT_FOUND', 'Item not found.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_OVERWRITE_FILE', 'Cannot override file.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_OVERWRITE', 'File overwrite successful.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_OVERWRITE_FILE', 'Cannot override file.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_INFOS_OVER_QUOTA', 'You have reached or passed your maximum quota for this course. You will have to delete some files before you will be able to upload again.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_SELECT_ONE_ITEM', 'Only <em>one</em> item must be selected.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_UNKNOWN', 'An undetermined error has occurred.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FOLDER_NOT_CREATED', 'The folder " %s " could not be created.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_BAD_FOLDER_NAME', 'The folder name contains illegal characters. You may choose from alphanumeric characters and underscores, dashes or periods.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FOLDER_NOT_CREATED', 'The folder " %s " could not be created.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_CREATE_DIR', 'Cannot create content directory.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONTENT_DIR_CREATED', 'Content directory created successfully.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_OPEN_DIR', 'Unable to open content directory. You may try to <a href="tools/filemanager/new.php">create it now</a>.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILEUPLOAD_DONE', 'File(s) uploaded.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_NOT_SAVED', 'The file cannot be saved.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_SAVED', 'The file was successfully saved as <strong>%s</strong>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_FILE_EXISTS', 'The file <strong>%s</strong> already exists. Do you want to overwrite the file?', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_MAX_STORAGE_EXCEEDED', 'Adding this file exceeds the maximum course storage limit.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_TOO_BIG', 'The file size exceeds the limit of <strong>%s </strong>. Contact your Transformable Administrator to have this limit increased.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_EXISTS', 'The file <strong>%1$s</strong> already exists. The newly uploaded file was saved as <strong>%2$s</strong>.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_UPLOADED', 'File was successfully uploaded.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_NOT_EXIST', 'The selected file does not exist.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_BAD_FILE_TYPE', 'Unsupported file type. Plain Text or HTML files only.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_OPEN_FILE', 'Cannot open the file: <b> %s </b>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_NOT_DELETED', 'Error deleting file. Cannot delete file.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_DIR_NOT_DELETED', 'Cannot open directory to be deleted.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_DIR_NO_PERMISSION', 'Cannot delete folder. You may not have premission, or it may not be empty.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_DIR_DELETED', 'Folder was successfully deleted.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_FILE_DELETE', 'Are you sure you want to delete the following file(s)? <ul>%s</ul>', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_ILLEGAL', '%s files are not allowed.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_RENAME', 'File or directory cannot be renamed. Either a file or directory with that name already exists, the original file or directory does not exist, or the file or directory name has not changed.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_DIR_NOT_EXIST', 'Directory <strong>%s</strong> does not exist. Please create it.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_DIRS_MOVED', 'Directories successfully moved.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_MOVED_FILES', 'Files successfully moved.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_FILE_MOVE', 'Are you sure you want to move <strong>%1s</strong> to the folder <strong>%2s</strong>?', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DIR_MOVE', 'Are you sure you want to move <strong>%1s</strong> to the folder <strong>%2s</strong>?', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_ARCHIVE_EXTRACTED', 'Archive has been extracted successfully.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_NO_SPACE_LEFT', 'There is no more space in this course to extract this archive.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_UPLOADED_ZIP', 'File was successfully uploaded. You may now <a href="file_manager/zip.php?pathext=%1$s%5$sfile=%2$s%5$spopup=%3$s%5$s_course_id=%4$s">extract</a> the file.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_COURSE_CATEGORY', 'Are you sure you want to delete the following course categories? The courses in the deleted categories will be marked as Uncategorized.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_content', 'Add Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'arrange_content', 'Arrange Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'edit_content', 'Edit Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'preview', 'Preview', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'accessibility', 'Accessibility', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'processing', 'Processing', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'password_request2', 'Dear %1$s,\r\n\r\nYour login name is %2$s.\r\n\r\nTo set a new password, follow the link below. \r\n\r\n%4$s\r\n\r\n(If this link does not take you to the site, copy and paste it into the address bar of your internet browser)\r\n\r\nThe link will become invalid after %3$s days.', now(), 'password reminder');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'password_forgot', 'Forgot Password', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'password', 'Password', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'password_change_confirm', 'Your password on %s has been changed successfully. Go to %s to login.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'missing_content', 'Missing Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_sub_folder', 'Add Sub Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'add_sub_page', 'Add Sub Page', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'delete_this_folder', 'Delete This Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'content_folder_title', 'Content Folder Title', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'edit_content_folder', 'Edit Content Folder', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'previous_topic', 'Previous Topic', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'save_changes_unsaved', 'Unsaved changes have been made.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'save_changes', 'Save Changes', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'close_after_saving', 'Close after saving', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'formatting', 'Formatting', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'packaged_in', 'Content Package', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'new_window', 'Search opens in a new window.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'customized_head', 'Styles/CSS', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'customized_head_note', 'Edit your own styles or javascript', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'use_customized_head', 'Use Customized Head', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'paste_file', 'Paste From File', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'html_only', 'Plain Text or HTML files only.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'weblink', 'Web Link', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'content', 'Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'properties', 'Properties', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'alternative_content', 'Adapted Content', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'access_credit', 'Accessibility report provided by <a title="AChecker Web Accessibility Checker (link opens in a new window)" target="_new" href="http://www.achecker.ca">AChecker</a>.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'usaved_changes_made', 'Unsaved changes made', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'keywords', 'Keywords', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'about_content_tests', 'Link available tests to this content page.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'allow_test_export', 'Allow students to export tests with content packages:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'custom_test_message', 'Include a message to appear along with the link to the test.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'No_resources', 'No resources found in this content page.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'original_resource', 'Original resource', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'resource_type', 'Original Resource Type', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'alternatives', 'Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'text', 'Text', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'audio', 'Audio', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'visual', 'Visual', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'sign_lang', 'Sign Language', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'customized_head_enabled_title', 'Toggle Scripts/CSS', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'customized_head_disabled_title', 'Scripts/CSS disabled', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'paste_enabled_title', 'Toggle paste from file', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'paste_disabled_title', 'Paste from file disabled', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'fileman_enabled_title', 'Open File Manager window', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'fileman_disabled_title', 'File Manager disabled', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'accessibility_enabled', 'Acessibility Validation enabled', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'accessibility_disabled', 'Accessibility Validation disabled', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'processing', 'Processing', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'browse_for_upload', 'Browse for file to upload', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'the_follow_errors_occurred', 'The following errors occurred:', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'content_id', 'Content ID', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'put_link', 'put link name here', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'auditory', 'Auditory', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'textual', 'Textual', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'stop_apply_text_alternatives', 'Stop Applying Text Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'apply_audio_alternatives', 'Apply Audio Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'stop_apply_audio_alternatives', 'Stop Applying Audio Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'apply_text_alternatives', 'Apply Text Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'stop_apply_visual_alternatives', 'Stop Applying Visual Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'apply_visual_alternatives', 'Apply Visual Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'stop_apply_sign_lang_alternatives', 'Stop Applying Sign Language Alternatives', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', 'apply_sign_lang_alternatives', 'Apply Sign Language Alternatives', now(), '');

INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_template', '', '', now(), '');

INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_SENDING_ERROR', 'There was an error sending the email message.', now(), 'mail failed to be sent.');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_PASSWORD_CHANGED', 'Password changed successfully. You may now login using the new password.', now(), 'change password');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONFIRM_EMAIL2', 'An email with instructions on retrieving your password has been sent.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_EMAIL_NOT_FOUND', 'No account found with that email address.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_LINK', 'The link is either invalid or expired.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_MISSING_CONTENT', 'The requested content is missing.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_INFOS_NO_PAGE_CONTENT', 'There is no content on this page.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_ID_ZERO', 'Content ID was zero, or was missing.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_CONFIRM_SUB_CONTENT_DELETE', 'This content page has sub content. If you delete this page all its sub pages will be deleted as well.<br />', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONTENT_DELETED', 'Content was successfully deleted', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_INFOS_NO_TESTS', 'No tests found. Create tests using the "Test Manager".', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_FILE_PASTED', 'The file was successfully pasted into the textarea below. <strong><em>Save to apply changes</em></strong>, or Cancel to return to the previously saved content.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_FILE_NOT_SELECTED', 'You did not select a file to upload.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_BAD_FILE_TYPE', 'Unsupported file type. Plain Text or HTML files only.', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_INPUT', 'Invalid URL: %s', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CLOSED', 'Successfully closed', now(), '');

INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');
INSERT INTO `TR_language_text` VALUES ('en', '_msgs','TR_', '', now(), '');


INSERT INTO `AT_language_text` VALUES ('en', '_msgs','AT_ERROR_TILE_AUTHENTICATION_FAIL','The Transformable authentication fails at:<br />%s.',now(),'');
INSERT INTO `AT_language_text` VALUES ('en', '_msgs','AT_ERROR_TILE_IMPORT_FAIL','Transformable course import failed at:<br />%s.',now(),'');
INSERT INTO `AT_language_text` VALUES ('en', '_msgs','AT_FEEDBACK_TILE_IMPORT_SUCCESS','The course is imported into Transformable successfully. <br /><a href="%s" target="_new">View imported course at Transformable</a>',now(),'');
INSERT INTO `AT_language_text` VALUES ('en', '_template','wrong_request_token','Mismatched request token from OAuth server.',now(),'');
INSERT INTO `AT_language_text` VALUES ('en', '_template','tile_not_accessible','Transformable repository is not accessible.',now(),'');
INSERT INTO `AT_language_text` VALUES ('en', '_template','tile_howto','Enter the keywords to search Transformable repository.',now(),'');
