# Table structure for table 'language_text'
#

CREATE TABLE `language_text` (
  `language_code` varchar(5) NOT NULL default '',
  `variable` varchar(30) NOT NULL default '',
  `term` varchar(50) NOT NULL default '',
  `text` blob NOT NULL,
  `revised_date` datetime NOT NULL default '0000-00-00 00:00:00',
  `context` text NOT NULL,
  PRIMARY KEY  (`language_code`,`variable`,`term`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;

INSERT INTO `language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_ITEM','Are you sure you want to delete the following items? <strong>%s</strong>','2009-03-17 15:19:54','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_LANG','Are you sure you want to delete the language (<strong>%s</strong>)?','2009-02-23 15:13:50','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_MYOWN_UPDATE','Are you sure you want to <strong>delete</strong> update <strong>%s</strong>?','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_USER','Are you sure you want to delete the following users? <strong>%s</strong>','2009-02-06 11:58:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_CONFIRM_DELETE_USER_GROUP','Are you sure you want to delete the following user groups? <strong>%s</strong>','2009-02-12 15:08:53','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_ACCOUNT_DISABLED','That account has been disabled.','2009-01-08 11:43:51','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_CONNECT','Cannot connect to URL: %s','2009-04-22 09:26:45','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_DEL_DEFAULT_LANG','Cannot delete default language <strong>%s</strong>. The system cannot run properly without it.','2009-02-23 15:47:44','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CANNOT_UNZIP','Can NOT unzip the uploaded file.','2009-06-22 14:49:02','error msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CHOOSE_ACTION','Please choose action for file <strong>%s</strong>','2009-06-22 14:49:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CHOOSE_UNINSTALLED_UPDATE','Please choose an uninstalled update.','2009-06-22 14:49:02','Updater: error msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_CONFIRM_BAD','Your email address and account could not be confirmed.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_DB_NOT_UPDATED','Information could not be added to the database.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMAIL_EXISTS','An account with that email address already exists.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMAIL_INVALID','Email address was invalid.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMAIL_NOT_FOUND','No account found with that email address.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_FIELD','Field cannot be empty. Data is not saved.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_FIELDS','The following required field(s) are empty:<br />\r\n%s.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_SESSIONID','Empty Session ID.','2009-03-03 13:44:57','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_USER','Empty user.','2009-03-03 13:44:57','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_EMPTY_WEB_SERVICE_ID','Empty web service ID.','2009-03-04 14:53:18','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_FIRST_LAST_NAME_UNIQUE','First, second, and last names combination must be unique.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_FORMAT','Invalid format.','2009-03-03 13:44:57','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_LOGIN','Invalid login/password combination.','2009-01-08 11:43:51','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_SESSION','Invalid session.','2009-03-03 13:44:57','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_TOKEN_TYPE','Invalid token type.','2009-10-09 16:18:01','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_INVALID_WEB_SERVICE_ID','Invalid web service ID.','2009-03-04 14:49:59','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_LANG_EMPTY','The text for this language has not been translated yet.','2009-02-24 13:57:01','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_LANG_EXISTS','The language you are trying to create already exists.','2009-02-24 09:20:45','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_LANG_WRONG_VERSION','The language pack you are trying to import is not compatible with this version of Transformable.','2009-02-24 13:58:25','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_LOGIN_CHARS','Your Login Name must only contain letters, numbers, periods, or underscores (_\'s).','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_LOGIN_EXISTS','That login already exists, please choose another.','2009-01-09 11:34:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_NOT_LOCALHOST','Sorry, the IP address of localhost is not public. For security reasons, validating resources located at non-public IP addresses has been disabled in this service.','2009-04-22 09:26:45','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_NO_ACTION_SELECTED','No action selected.','2009-02-04 15:31:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_NO_ITEM_SELECTED','You must select an item before using a button.','2009-02-04 15:31:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_PAGE_NOT_FOUND','Page (%s) cannot be found','2008-12-12 13:28:09','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_PASSWORD_CHARS','The password must contain letters, numbers, and symbols.','2009-01-09 13:41:06','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_PASSWORD_LENGTH','Password must be at least 8 characters long.','2009-01-09 13:41:06','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_PASSWORD_MISMATCH','Passwords did not match.','2009-01-09 13:41:06','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_REMOVE_WRITE_PERMISSION','Please remove write permission from the listed files.','2009-06-22 14:49:02','error msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_SECRET_ERROR','Letters or numbers entered from the CAPTCHA image are incorrect. Try again.','2009-10-22 14:06:59','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_SELECT_ONE_ITEM','Only <em>one</em> item must be selected.','2009-02-04 15:31:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_SENDING_ERROR','There was an error sending the email message.','2009-01-16 13:14:08','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_UPDATE_ALREADY_INSTALLED','The selected update is already installed.','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_UPDATE_DEPENDENCY','Due to update dependency, please install the listed updates before installing this update: %s','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_UPDATE_XML_NOT_FOUND','Update XML file is not found.','2009-06-22 14:49:02','error msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_ERROR_WRONG_PASSWORD','Incorrect password.','2009-01-16 10:29:47','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_ACCOUNT_CONFIRMED','Account has been confirmed.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_ACTION_COMPLETED_SUCCESSFULLY','Action completed successfully.','2009-01-16 11:29:41','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CANCELLED','Successfully cancelled without any changes.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CHANGE_TO_SAME_EMAIL','The email address is same as what you currently have.','2009-01-16 11:54:46','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONFIRMATION_SENT','An email confirmation message has been sent.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONFIRM_EMAIL2','An email with instructions on retrieving your password has been sent.','2009-01-16 13:14:08','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_CONFIRM_GOOD','Your email address has been confirmed successfully.','2009-01-14 14:40:42','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_IMPORT_LANG_SUCCESS','New language was successfully imported.','2009-02-24 13:58:25','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_LOGIN_SUCCESS','You have logged in successfully.','2009-01-08 11:43:51','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_LOGOUT','You have successfully been logged out.','2009-01-08 09:38:14','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_ONLY_ENGLISH','Only English language is defined in the system. There is no foreign languages to translate.','2009-02-18 11:52:10','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_PASSWORD_CHANGED','Password changed successfully.','2009-01-16 10:35:40','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_PROFILE_UPDATED','Your Profile was successfully updated.','2009-01-15 10:59:58','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_REGISTER_SUCCESS','You have registered successfully. Your web service ID is %s. This ID must be presented when using web service. This ID can always be retrieved from \"Profile\" page.','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_REG_THANKS_CONFIRM','Thank-you for registering. Please follow the instructions in the email we sent you on how to confirm your account. You will need to confirm your account before you can login.','2009-01-09 14:07:11','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_UPDATE_CREATED_SUCCESSFULLY','The update has been created successfully.','2009-06-22 14:49:02','Updater: feedback msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_FEEDBACK_UPDATE_INSTALLED_SUCCESSFULLY','The update has been installed successfully.','2009-06-22 14:49:02','Updater: feedback msg');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_ADD_EDIT_LANGUAGE','<h2>Add/Edit Language</h2>\r\n\r\n	<p>Adding and Editing the language properties allows users to change the following:\r\n	<ul>\r\n		<li>Language Code (3 digit ISO-639-2 language code)</li>\r\n		<li>Locale (two letter abritrary code to represent a variation of a language)</li>\r\n		<li>Character Set (should always be UTF-8)</li>\r\n		<li>Regular Expression (leave blank)</li>\r\n		<li>Language name translated</li>\r\n		<li>Language name in English</li>\r\n		<li>Status (enabled/disabled)</li>\r\n	</ul>\r\n	</p>\r\n	<p>When \"Status\" is set to enabled, the language is displayed in the selector at the bottom of Transformable pages, which allows users to switch to this language.</p>\r\n','2009-04-15 09:46:37','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_CHANGE_EMAIL','<h2>Change Email</h2>\r\n<p>This page allows users to change email addresses. </p>\r\n','2009-04-15 09:47:18','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_CHANGE_PASSWORD','<h2>Change Password</h2>\r\n<p>This page allows users to change passwords. The form authenticates users by checking their old password first, and then setting a new password and typing it again.</p>\r\n','2009-04-15 09:53:55','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_CREATE_EDIT_USER ','<h2>Create/Edit User</h2>\r\n\r\n<p>All fields on \"Create User\" and \"Edit User\" forms are required. Most fields are self-explanatory. When the \"Account Status\" field is set to disabled, the user is not able to login. </p>\r\n<p>User accounts can also be created by individuals using the Registration form available through the public pages of Transformable. The accounts created via the Registration form are automatically set to user group \"Regular User\". </p>','2009-06-04 13:00:03','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_CREATE_EDIT_USER_GROUP','<h2>Create/Edit User Group</h2>\r\n\r\n<p>All fields are relatively self-explanatory.</p>\r\n\r\n<p>There are six privileges provided by Transformable. Privileges are fixed and not changeable.\r\n	<dl>\r\n		<dt>Home</dt>\r\n		<dd>This is where user implements own functions.</dd>\r\n		<dt>User Management</dt>\r\n		<dd>Create, edit, delete users.</dd>\r\n		<dt>Language Management</dt>\r\n		<dd>Create, edit, delete, enable, disable languages.</dd>\r\n		<dt>Translation</dt>\r\n		<dd>Translate all Transformable terms into languages other than English, or edit existing English text.</dd>\r\n		<dt>Profile Management</dt>\r\n		<dd>Edit profile, change password or email.</dd>\r\n	</dl>\r\n</p>','2009-06-04 13:05:21','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_CREATE_UPDATE','<h2>Creating Update</h2>\r\n\r\n<p>If you happen to come across a bug you can fix, or have a new feature you would like added to the Transformable public distribution, you can use Create Update to put your changes into a form that can be easily added to the Transformable public code. Or, if you have a feature you are adding to one Transformable installation that you would like to have added to another, Create Update is ideal for reproducing your feature across installations. If you are creating new features that are not going to become part of the Transformable public source code, you can build them into a update so they can be reapplied from version to version as you upgrade your Transformable system. Creating updates does require knowledge of PHP, and of SQL if you plan on creating a update that changes the Transformable database. Please refer to the appropriate documentation for information on PHP and SQL. <p>\r\n\r\n<dl>\r\n	<dt>Transformable Update ID</dt>\r\n	<dd>The update id you give to your update must be different from all updates available for the particular version of Transformable it applies to. It is suggested you prefix your updates with a special identifier that represents the author or the authoring organization. If for example the University of Toronto is creating the update, a update ID might look like \"uoft_0002.\"</dd>\r\n	<dt>Transformable Version to Apply</dt>\r\n	<dd>This needs to be the exact version number of the Transformable version the update applies to (e.g 1.6). including any minor version numbers (e.g 1.6.1.2)  The exact version number can be found on the Administrator open screen under \"Statistics and Information.\" In most cases when applying a update created for an older version of Transformable, the \"Transformable version to Apply\" will need to be adjusted. Or, this can be adjusted manually in the patch.xml file included with the source code of the update.\r\n	</dd>\r\n	<dt>Description</dt>\r\n	<dd>This should be a detailed description of what the update does. Example might include \"fixes problem uploading files to filemanager\" for a bug fix, or \"added a timer function to tests\" for an added feature, or \"removes registration tab\" for a feature adjustment, etc. Include enough detail so those applying the update understand exactly what it will do..</dd>\r\n	<dt>SQL Statement</dt>\r\n	<dd>This optional field can be used to insert SQL commands which modify the Transformable database. It might be used to write an SQL statement to modify and existing table, such as changing a data type, or a field size, or to add or remove an field. It can also be used to insert SQL that generates a new table for a new feature created by a update, or it can be used to insert data into a table used by a feature created by the update. Any SQL can be included in this field. Be careful when running SQL, that that SQL is not going to interfere with upgrade SQL. If you are changing table structures and those same tables are being altered during an upgrade, the upgrade may fail.</dd>\r\n	<dt>Dependant Updates</dt>\r\n	<dd>It is common for later updates to require changes from earlier updates before they can be installed. If this is the case for the update you are creating, enter the update IDs into the Dependant Update ID field. Click on Add Dependent Update if additional dependencies are required. Be sure to check the updates on the opening screen of the Updater to see if the file you are modifying with your update is  being modified by an update.Transformable.ca update. If they are modifying the same files, you may need to include the ID numbers for those updates in the Dependant Updates for the update your are creating.</dd>\r\n	<dt>Files</dt>	\r\n	<dd>This area is where most Transformable updates are created. Click on <strong>Add File</strong>  to generate a update block. A update block can include one of four actions on the file being modified, as described below. As many update blocks as required can be added to a update. </dd>\r\n		<dl>\r\n	<dt>Add File</dt>\r\n	<dd>The <strong>Add</strong> action can be used to add a new file to Transformable. This action is often used in conjuction with other update blocks that alter or delete files, to add a replacement file for one deleted, or to perhaps add a required or include file needed by a modified section in the file being changed. In the <strong>File Name</strong> field enter the file name to be assigned to the file when it is installed. In the <strong>Directory</strong> field enter the <i>relative path</i> from the Transformable root directory in which the modified file is or will exist. Select  from <strong>Upload File</strong> using the Browse button to locate the file in your local computer\'s file system. Note that the upload file can have any name. It will be renamed to the file name listed in the File Name field when it is installed.</dd>\r\n	<dt>Alter File</dt>\r\n	<dd>This option is used when you wish to make changes to a piece of code within an existing source code file. In the <strong>File Name</strong> field enter the name of the file in the Transformable source code that will be altered. In the <strong>Directory</strong> field enter the relative path to the directory in which the to be alter file exists, relative to the Transformable root directory. In the <strong>Code To Replace From</strong> field copy the code from the original file the will be replaced, or appended to, and in the <strong>Code To Replace To</strong> field enter to code that will replace the code above in the <i>From</i> field. Or, if you are adding code instead of replacing code, include the code from the field above so it gets added back if you are only using that code as a way of identifying a location in the file where new code is being added.</dd>\r\n	<dt>Delete File</dt>\r\n	<dd>This option will remove files from Transformable. In the <strong>File Name</strong>  field enter the name of the file to be deleted. In the <strong>Directory</strong> field enter the path to the directory in which the to be delete file exists, relative to the root directory of the Transformable installation. </dd>\r\n	<dt>Overwrite File</dt>\r\n	<dd>This option is used to replace an existing file in Transformable with a new one. In the <strong>File Name</strong>  field enter the name of the file to be replaced. In the <strong>Directory</strong> field enter the path to the directory in which the to be replaced file exists, relative to the root directory of the Transformable installation. In the <strong>Upload File</strong> field use the Browse button to choose a file from your local computer to replace the specified file. The upload file may be named anything. It will be renamed to the file it is replacing when the update is installed.</dd>\r\n	</dl>\r\n	<dt>Create Update</dt>\r\n	<dd>Click on this button to build the update into a downloadable zip file. This zip file can then be uploaded in the Upload field on the main Updater screen to apply a update to a system.</dd>\r\n	<dt>Save Update</dt>\r\n	<dd>Click on this button to save the developing update to the Transformable database for future reference. Though it is not required, you should save a copy of the update in this way, so it can be retrieved and edited if necessary. Or, if a update takes more than a single sitting to build, you can save it, then retrieve it later to continue.</dd>\r\n	<dt>Cancel</dt>\r\n	<dd>Press this button to ignore the latest changes to the update, and return to My Own Updates Screen.</dd>\r\n\r\n</dl>','2009-06-22 15:32:56','Updater');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_LANGUAGE','<h2>Language Management</h2>\r\n\r\n	<p>Transformable can be displayed in many different languages! Through the Language Manager language packs can be selected and imported.</p>\r\n\r\n<h3>Managing Existing Languages</h3>\r\n	<p>Installed languages can be edited, deleted, or exported as an Transformable language pack for redistribution. When exporting a language, a download prompt will appear asking to download a zip file of the language pack.</p>\r\n	<p>Note that the English language (language code: eng) cannot be deleted. This is the base language pack that ensures Transformable runs properly. When other languages are installed, users can disable it if they don\'t want Transformable to be displayed in English.</p>\r\n	\r\n<h3>Importing Languages</h3>\r\n	<p>Language packs can be imported by retreiving the package and then importing it into Transformable.</p>\r\n	<ol>\r\n		<li>Visit <a href=\"http://www.atutor.ca/transformable/translate/index.php\" target=\"_new\">Transformable Language Packs</a> to download one of the available language packs for your version.</li>\r\n		<li>Use the <code>Browse...</code> button to find the downloaded language pack.</li>\r\n		<li>Use the <code>Import</code> button to import the language.</li>\r\n	</ol>\r\n\r\n	<p>You can contribute to the Transformable community by exporting a language pack from your Transformable installation, and attaching it to a message in the atutor.ca <a href=\"http://atutor.ca/forum/4/1.html\">Translation Forum</a>. Also see the <a href=\"http://atutor.ca/atutor/docs/translate.php\">Translator Documentation</a> for further details about translating Transformable.</p>','2009-06-04 13:08:15','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_LOGIN','<h2>Login</h2>\r\n\r\n<p>A user may login to Transformable with their Login Name or Email address, and the Password entered during <a href=\"../register.php\">registration</a>. Logging in gives users access to use more functions provided to regular user.</p>\r\n','2009-04-15 09:51:28','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_PASSWORD_REMINDER','<h2>Forgot Your Password</h2>\r\n\r\n<p>If you have forgotten your password, use the <em>Forgot your password?</em> link on the Login screen. The form will email the login name to you, along with a link you must follow to change your password.</p>\r\n','2009-04-15 09:51:37','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_PROFILE','<h2>Profile</h2>\r\n<p>This section allows a user to change elements of his/her personal profile.</p>\r\n\r\n<p>Although the login name cannot be altered, password, email address, and other personal information are editable.</p>\r\n','2009-04-15 09:51:47','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_REGISTRATION','<h2>Register</h2>\r\n\r\n<p>In order for a user to login to the Transformable system and save results from accessibility reviews, manage translate or administer the system, a unique system account needs to be created.  Use the <em>Register</em> link on the login screen to access the registration form. If email-confirmation has been enabled by the system administrator, a message will be sent to the email address entered, containing a link that must be followed to confirm the new account. Once this has been done, the login name or email address, and the password entered during registration can now be used on the <a href=\"../login.php\">Login</a> screen.</p>','2009-04-15 09:52:02','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_TRANSLATION','<h2>Translation</h2>\r\n\r\n	<p>All fields are self-explanatory. Note that language drop down box lists all the languages defined in the current installation of Transformable, no matter the language status (enabled or disabled). If you are translating a new language for Transformable, first define the language using the Language management tool\'s Add Language feature. If you do not have access to the Language management tools, ask your Transformable administrators to add the language.</p>\r\n\r\n<p>You can contribute to the Transformable community by exporting a language pack from your Transformable installation, and attaching it to a message in the atutor.ca <a href=\"http://atutor.ca/forum/4/1.html\">Translation Forum</a>. Also see the <a href=\"http://atutor.ca/atutor/docs/translate.php\">Translator Documentation</a> for further details about translating Transformable.</p>','2009-06-04 13:17:38','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_UPDATER','<h2>Updater</h2>\r\n	<p>The Updater was introduce in Transformable 1.6 to allow administrators to update their systems with feature adjustments, security fixes, and other Transformable code changes in between Transformable releases. The Updater is included as a standard module with Transformable 1.6.1+, and installs as an extra module for 1.6.</p>\r\n<dl>\r\n	<dt>The Update List</dt>\r\n	<dd>On the opening screen of the Updater will appear a list of updates available for the version of Transformable you are using, along with a description of each update.  This list is retrieved from update.atutor.ca, as are the updates themselves, so you must be connected to the Internet. Updates are retrieved from update.atutor.ca by Transformable and applied as necessary. </dd>\r\n	<dt>File Permissions</dt>\r\n	<dd>In most cases you will be asked to temporarily grant write permission to the files that need to be updated or replaced, then once the update has been applied, you will be asked to change the permissions back to read only. It is important that you follow the instructions after updates have been applied, otherwise you run the risk of opening a security hole. \r\n	</dd>\r\n	<dt>Types of Updates</dt>\r\n	<dd>Updates come in various forms. Some updates replace code in a file with new code. Others replace a file with a new file.  Others may do both on multiple files and multiple code changes. Other updates delete files that are no longer required.</dd>\r\n	<dt>Required and Non-Required Updates</dt>\r\n	<dd>In most cases you will want to install updates in the order they appear in the update list, but not all updates are required updates.  Some feature updates can be ignored if you do not need the features they would add or modify on your system. Other updates will have dependencies, requiring the administrator to install earlier updates before installing a later one. You will be prompted to install previous updates if there are dependencies.</dd>\r\n	<dt>Checks and File Backups</dt>\r\n	<dd>If you have made changes to a file the Updater wishes to change,  you will be prompted to continue or not. The updater compares your local file with the same file in the Transformable code repository, and if they differ the prompt will display. In many cases  the Updater can apply updates without changing the code you have modified, but if the code to be replaced was modified, the update will fail, or if the update replaces a file, your changes will be lost. In all cases the updater will create a backup of the files that were modified, identified by the filename plus the update number added as a suffix. Rename the file to its original name to restore that file back to its original state. You can list these files by clicking the view messages button next to the update listing after the update is installed. After you have confirmed that the updates were applied and are working properly, it is safe to delete the backup files, though it does not hurt to keep them around. </dd>\r\n	<dt>Private Updates</dt>\r\n	<dd>In some cases private updates can be applied by uploading a update file through the upload form below the update list.  Private updates are often those used to apply changes that are not being applied to the Transformable default source code, or to apply custom features, or to share updates between users, etc. When uploading a update, be sure the update id, defined in the patch.xml file, is unique . </dd>\r\n</dl>','2009-06-22 15:37:42','Updater');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_USER','<h2>User Management</h2>\r\n\r\n	<p>This section allows administrators to manage all user accounts. Each user belongs to a user group to which privileges are assigned.</p>\r\n\r\n<p>There are three types of default user groups that are created when Transformable is installed. These are described below along with the default privileges associated with each groups. \r\n	<dl>\r\n		<dt>Administrator</dt>\r\n		<dd>Administrators have privileges to use the Home, manage users, languages and manage their own profile.</dd>\r\n		<dt>Regular User</dt>\r\n		<dd>Regular users have privileges to use the Home and manage their own profile.</dd>\r\n		<dt>Translator</dt>\r\n		<dd>Translators have privileges to use the Home, translate Transformable terms from English to other languages, and to manage their own profile. The languages that can be used in the system are defined by users who have \"Language Management\" privileges.</dd>\r\n	</dl>\r\n</p>\r\n\r\n<h3>Creating User Accounts</h3>\r\n\r\n<p>The users who belong to a group that has \"User Management\" privileges can manually add users to the system by using <em>Create User</em>.</p>\r\n<p>User accounts can also be created by individuals using the Registration form available through the public pages of Transformable. The accounts created via the Registration form are automatically set to user group \"Regular User\". </p>\r\n\r\n<h3>User Group</h3>\r\n\r\n<p><em>User Group</em> is used to create new user groups and edit existing user groups.</p>','2009-06-04 12:55:56','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_USER_GROUP ','<h2>User Group</h2>\r\n\r\n<p>The User Group section allows administrators to manage user groups. User groups define the privileges that are granted to the users who are members of a group. Note that \"Administrator\" and \"Regular User\" groups can not  be deleted. They must exist for Transformable\'s proper operations. All other groups are optional.</p>\r\n\r\n<p>There are three default user groups in Transformable. Below is a description of the default privileges that are granted to each group. The privileges in user groups are editable by users who are a member of a group that has the \"User Management\" privilege.\r\n<dl>\r\n<dt>Administrator</dt>\r\n<dd>Administrators have privileges to use the Home, manage users, languages and manage their own profile.</dd>\r\n<dt>Regular User</dt>\r\n<dd>Regular users have privileges to use the Home and manage their own profile. </dd>\r\n<dt>Translator</dt>\r\n<dd>Translators have privileges to use the Home, translate Transformable terms from English to other languages, and to manage their own profile. The languages that can be used in the system are defined by users who have \"Language Management\" privileges.</dd>\r\n</dl>\r\n</p>','2009-06-04 13:04:37','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_HELP_USER_PASSWORD ','<h2>Change Password</h2>\r\n\r\n<p>All fields are required and self-explanatory. Once the new password is set successfully, an email notification is sent to the user.</p>\r\n','2009-04-15 09:53:11','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_INFOS_INVALID_USER','You must <a href=\"login.php\">login</a> to use this section.','2009-01-15 16:13:14','');
INSERT INTO `language_text` VALUES ('en', '_msgs','TR_INFOS_UPDATE_INSTALLED_AND_REMOVE_PERMISSION','The update has been installed. Please remove write permission as instruction.','2009-06-22 14:49:02','Updater: info msg');
INSERT INTO `language_text` VALUES ('en', '_template','15_max_chars','15 character maximum','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','20_max_chars','20 character maximum','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','add','Add','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','add_a_file','Add A File','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','add_dependent_update','Add A Dependent Update','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','add_edit_group','Add/Edit Group','2009-04-08 15:20:56','');
INSERT INTO `language_text` VALUES ('en', '_template','add_edit_language','Add/Edit Language','2009-02-23 13:27:38','');
INSERT INTO `language_text` VALUES ('en', '_template','add_language','Add Language','2009-02-18 15:56:02','');
INSERT INTO `language_text` VALUES ('en', '_template','add_privileges','Add Privileges','2009-02-17 09:45:53','');
INSERT INTO `language_text` VALUES ('en', '_template','transformable','Transformable','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','transformable_documentation','Transformable Documentation','2009-06-16 10:25:25','');
INSERT INTO `language_text` VALUES ('en', '_template','transformable_handbook','Transformable Handbook','2009-01-28 15:28:06','');
INSERT INTO `language_text` VALUES ('en', '_template','transformable_version_to_apply','Transformable Version to Apply','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','transformable_whatis','Transformable provides a basic frame to build an application. It has build-in functions to support multiple languages, translation, user/user group managment, updater and user profile managment.','2009-05-29 08:55:24','');
INSERT INTO `language_text` VALUES ('en', '_template','all','All','2008-11-27 09:49:41','');
INSERT INTO `language_text` VALUES ('en', '_template','alter','Alter','2009-06-22 14:49:02','');
INSERT INTO `language_text` VALUES ('en', '_template','audible_captcha','Audible Version of CAPTCHA','2009-10-22 14:02:18','');
INSERT INTO `language_text` VALUES ('en', '_template','author','Author','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','available_to','Available To','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','available_updates','Available Updates','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','back_to','Back To:','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','calendar','Calendar','2009-04-06 10:43:09','');
INSERT INTO `language_text` VALUES ('en', '_template','cancel','Cancel','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','change_email','Change Email','2009-01-15 11:29:34','');
INSERT INTO `language_text` VALUES ('en', '_template','change_password','Change Password','2009-01-15 11:29:34','');
INSERT INTO `language_text` VALUES ('en', '_template','charset','Character Set','2009-02-20 11:43:44','');
INSERT INTO `language_text` VALUES ('en', '_template','choose_lang','Choose a language to translate','2008-11-26 10:11:15','');
INSERT INTO `language_text` VALUES ('en', '_template','close_popup','Close Popup','2009-01-28 15:28:06','');
INSERT INTO `language_text` VALUES ('en', '_template','code_to_replace_from','Code To Replace From','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','code_to_replace_to','Code To Replace To','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','combination','Use a combination of letters, numbers and symbols','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','confirm_delete','Are you sure you want to delete these records?','2009-04-09 11:29:46','');
INSERT INTO `language_text` VALUES ('en', '_template','consumer','Consumer','2009-10-08 15:42:55','');
INSERT INTO `language_text` VALUES ('en', '_template','contact_email','Contact Email','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','contain_only','May contain only letters, numbers, underscores, hyphens or periods.','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','continue','Continue','2009-06-22 14:49:02','');
INSERT INTO `language_text` VALUES ('en', '_template','copyright','Web site engine\'s code is copyright &copy; 2009','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','create_edit_update','Create/Edit Update','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','create_edit_user','Create/Edit User','2009-02-05 10:25:08','');
INSERT INTO `language_text` VALUES ('en', '_template','create_edit_user_group','Create User Group','2009-02-18 11:13:36','');
INSERT INTO `language_text` VALUES ('en', '_template','create_update','Create Update','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','create_user','Create User','2009-01-21 15:58:32','');
INSERT INTO `language_text` VALUES ('en', '_template','date','Date','2009-02-27 16:07:19','');
INSERT INTO `language_text` VALUES ('en', '_template','date_created','Date Created','2009-02-17 12:02:27','');
INSERT INTO `language_text` VALUES ('en', '_template','default_language','Default Language','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','default_max_file_size','Default: 1048576','2009-10-21 15:25:08','');
INSERT INTO `language_text` VALUES ('en', '_template','default_use_captcha','Default: Disable','2009-10-21 15:25:08','');
INSERT INTO `language_text` VALUES ('en', '_template','delete','Delete','2009-01-22 16:02:07','');
INSERT INTO `language_text` VALUES ('en', '_template','delete_language','Delete Language','2009-02-18 15:56:02','');
INSERT INTO `language_text` VALUES ('en', '_template','delete_this_file','Delete This File','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','delete_update','Delete Update','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','delete_user','Delete User','2009-02-06 11:41:23','');
INSERT INTO `language_text` VALUES ('en', '_template','delete_user_group','Delete User Group','2009-02-12 15:08:53','');
INSERT INTO `language_text` VALUES ('en', '_template','dependent_updates','Dependent Updates','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','dependent_update_id','Dependent Update ID','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','dependent_update_not_installed','<br><span style=\"color: red\">Waring: Due to update dependency, please install the listed updates first: </span>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','description','Description','2008-11-24 14:25:44','');
INSERT INTO `language_text` VALUES ('en', '_template','directory','Directory','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','disable','Disable','2009-01-20 11:47:15','');
INSERT INTO `language_text` VALUES ('en', '_template','disabled','Disabled','2009-01-20 11:45:23','');
INSERT INTO `language_text` VALUES ('en', '_template','done','Done','2009-06-22 16:16:50','');
INSERT INTO `language_text` VALUES ('en', '_template','edit','Edit','2009-01-22 16:02:07','');
INSERT INTO `language_text` VALUES ('en', '_template','edit_function','Edit Function','2009-03-17 14:58:36','');
INSERT INTO `language_text` VALUES ('en', '_template','edit_profile','Edit Profile','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','edit_update','Edit Update','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','email','Email','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','email_address','Email Address','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','email_confirmation_message','You have registered for an account on %1s. Please finish the registration process by confirming your email address by using the following link: %2s .','2009-01-14 13:25:55','');
INSERT INTO `language_text` VALUES ('en', '_template','email_confirmation_message2','To finish changing your account\'s email address on %1s, please confirm your email address by using the following link: %2s .','2009-01-16 11:07:44','');
INSERT INTO `language_text` VALUES ('en', '_template','email_confirmation_subject','Email Confirmation','2009-01-14 13:25:55','');
INSERT INTO `language_text` VALUES ('en', '_template','empty_param_consumer','Empty parameter \"consumer\".','2009-10-08 11:43:50','');
INSERT INTO `language_text` VALUES ('en', '_template','enable','Enable','2009-01-20 11:47:15','');
INSERT INTO `language_text` VALUES ('en', '_template','enabled','Enabled','2009-01-20 11:45:23','');
INSERT INTO `language_text` VALUES ('en', '_template','english_context','English Context','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','english_text','English Text','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','error','Error','2008-11-24 14:25:44','');
INSERT INTO `language_text` VALUES ('en', '_template','errors','Errors','2009-03-09 09:55:45','');
INSERT INTO `language_text` VALUES ('en', '_template','error_type','Error Type','2009-01-21 12:38:17','');
INSERT INTO `language_text` VALUES ('en', '_template','expand_add_privileges','Expand Add Privileges','2009-02-17 09:45:53','');
INSERT INTO `language_text` VALUES ('en', '_template','expected_result','Expected Result','2008-11-24 14:25:44','');
INSERT INTO `language_text` VALUES ('en', '_template','export','Export','2009-02-24 13:58:06','');
INSERT INTO `language_text` VALUES ('en', '_template','factory_default','Reset to Factory Defaults','2009-10-21 16:15:03','');
INSERT INTO `language_text` VALUES ('en', '_template','file','File','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','files','Files','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','file_name','File Name','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','filter','Filter','2008-11-27 09:48:36','');
INSERT INTO `language_text` VALUES ('en', '_template','first_name','First Name','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','get_my_update','Get My Update','2009-06-22 14:49:01','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','grant_write_permission','Please grant <strong>write</strong> permission to folders and files listed below:<p><strong>Note:</strong> To change permissions on Unix use <kbd>chmod a+rw</kbd> then the file name.</p>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','handbook_toc','Handbook Toc','2009-01-28 15:28:06','');
INSERT INTO `language_text` VALUES ('en', '_template','hide_contents','Hide Contents','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','home','Home','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','illegal_extentions','Illegal File Extensions','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','image_validation_text','In the above image there are numbers and/or letters displayed.  Please type them into the following field.','2009-10-22 14:02:18','');
INSERT INTO `language_text` VALUES ('en', '_template','image_validation_text2','This helps ensure a live person is registering on this system.','2009-10-22 14:02:18','');
INSERT INTO `language_text` VALUES ('en', '_template','import','Import','2009-02-18 15:56:02','');
INSERT INTO `language_text` VALUES ('en', '_template','import_a_new_lang','Import a New Language','2009-02-24 13:58:06','');
INSERT INTO `language_text` VALUES ('en', '_template','info','Information','2009-03-06 11:29:10','');
INSERT INTO `language_text` VALUES ('en', '_template','input','Input','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','install','Install','2009-06-22 14:49:03','');
INSERT INTO `language_text` VALUES ('en', '_template','installed_date','Installed Date','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','interface_terms','Interface Terms','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','jump_to_content','Jump to Content','2009-05-25 10:17:46','');
INSERT INTO `language_text` VALUES ('en', '_template','language','Language','2009-04-14 10:35:06','');
INSERT INTO `language_text` VALUES ('en', '_template','lang_code','Language Code','2009-02-20 11:43:44','');
INSERT INTO `language_text` VALUES ('en', '_template','last_login','Last Login','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','last_modified','Last Modified','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','last_name','Last Name','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','last_update','Last Update','2009-02-17 12:02:27','');
INSERT INTO `language_text` VALUES ('en', '_template','latex_server','MimeTex Server for the LaTex service','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','latex_server_info','For production purposes, please install mimeTeX on your own server.','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','lesson_builder','Lesson Builder','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','locale','Locale','2009-02-23 13:27:38','');
INSERT INTO `language_text` VALUES ('en', '_template','login','Login','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','login_name','Login Name','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','login_name_or_email','Login Name or Email','2009-01-09 10:40:36','');
INSERT INTO `language_text` VALUES ('en', '_template','login_text','Enter the Login Name (or email) and Password you chose at registration.<br /><br /><br />Not registered yet? <a href=\"register.php\" >Register</a> Or, <a href=\"password_reminder.php\">Forgot your password?</a><br /><br />','2009-01-29 14:24:45','');
INSERT INTO `language_text` VALUES ('en', '_template','logout','Logout','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','match_all_words','Match All Words','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','match_any_word','Match Any Word','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','max_file_size','Maximum File Size','2009-10-21 15:25:22','');
INSERT INTO `language_text` VALUES ('en', '_template','msg_terms','Message Terms','2009-05-05 09:05:33','');
INSERT INTO `language_text` VALUES ('en', '_template','myown_updates','My Own Updates','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','na','N/A','2009-02-23 14:31:55','');
INSERT INTO `language_text` VALUES ('en', '_template','name','Name','2009-03-18 14:53:42','');
INSERT INTO `language_text` VALUES ('en', '_template','name_in_english','Language name in English','2009-02-20 11:43:44','');
INSERT INTO `language_text` VALUES ('en', '_template','name_in_language','Language name translated','2009-02-23 13:28:12','');
INSERT INTO `language_text` VALUES ('en', '_template','name_in_translated','Language name translated','2009-02-20 11:43:44','');
INSERT INTO `language_text` VALUES ('en', '_template','never','Never','2009-02-05 11:25:19','');
INSERT INTO `language_text` VALUES ('en', '_template','new_or_translated','New or Translated Terms','2008-11-27 09:48:36','');
INSERT INTO `language_text` VALUES ('en', '_template','new_password','New Password','2009-01-16 10:52:03','');
INSERT INTO `language_text` VALUES ('en', '_template','new_terms','New Terms','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','next_chapter','Next Chapter','2009-01-28 15:28:06','');
INSERT INTO `language_text` VALUES ('en', '_template','no','No','2009-01-21 12:38:17','');
INSERT INTO `language_text` VALUES ('en', '_template','none_found','None Found.','2009-01-21 15:06:01','');
INSERT INTO `language_text` VALUES ('en', '_template','not_installed','Not Installed','2009-06-22 14:49:03','');
INSERT INTO `language_text` VALUES ('en', '_template','no_results_found','No results found.','2009-01-21 12:38:17','');
INSERT INTO `language_text` VALUES ('en', '_template','oauth_authenticate','OAuth User Authenticate','2009-10-19 10:45:38','');
INSERT INTO `language_text` VALUES ('en', '_template','oauth_server','OAuth server','2009-10-08 15:42:55','');
INSERT INTO `language_text` VALUES ('en', '_template','oauth_server_api','OAuth Server API','2009-10-19 10:45:38','');
INSERT INTO `language_text` VALUES ('en', '_template','options','Options','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','or','Or','2009-10-22 16:02:10','');
INSERT INTO `language_text` VALUES ('en', '_template','overwrite','Overwrite','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','password','Password','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','password_again','Password Again','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','password_blurb','Enter your account\'s email address below and an email with instructions on retrieving your password will be sent to you. The email address must be the same as the one you used for registration.','2009-01-16 13:19:57','');
INSERT INTO `language_text` VALUES ('en', '_template','password_changed','Password Changed','2009-02-06 09:08:32','');
INSERT INTO `language_text` VALUES ('en', '_template','password_change_confirm','Your password on %s has been changed successfully. Go to %s to login.','2009-01-16 13:17:32','');
INSERT INTO `language_text` VALUES ('en', '_template','password_change_msg','Your password has been altered. Please use the information below.','2009-02-06 09:08:31','');
INSERT INTO `language_text` VALUES ('en', '_template','password_new_blurb','Enter a new password for your account.','2009-01-16 13:55:40','');
INSERT INTO `language_text` VALUES ('en', '_template','password_old','Old Password','2009-01-16 10:27:02','');
INSERT INTO `language_text` VALUES ('en', '_template','password_reminder','Password Reminder','2009-01-07 16:14:08','');
INSERT INTO `language_text` VALUES ('en', '_template','password_request2','Dear %1$s,\r\n\r\nYour login name is %1$s.\r\n\r\nTo set a new password, follow the link below.\r\n\r\n%4$s\r\n\r\n(If this link does not take you to the site, copy and paste it into the address bar of your internet browser)\r\n\r\nThe link will become invalid after %3$s days.','2009-01-16 13:05:25','');
INSERT INTO `language_text` VALUES ('en', '_template','previous_chapter','Previous Chapter','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','print_version','Print Version','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','privileges','Privileges','2009-02-12 14:15:23','');
INSERT INTO `language_text` VALUES ('en', '_template','profile','Profile','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','published_date','Published Date','2009-01-21 12:38:17','');
INSERT INTO `language_text` VALUES ('en', '_template','refresh_image','Refresh Image','2009-10-22 14:02:18','');
INSERT INTO `language_text` VALUES ('en', '_template','register','Register','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','registration','Registration','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','relative_directory','Directory is relative directory to Transformable root, for example: docs/images/ or tools/tests/. Leave empty if it is Transformable root directory.','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','remove','Remove','2009-01-23 14:04:46','');
INSERT INTO `language_text` VALUES ('en', '_template','remove_write_permission','<span style=\"color:red\">Please <strong>REMOVE</strong> write permission on the listed folders and files for your security:</span><p><strong>Note:</strong> To remove permissions on Unix use <kbd>chmod 755</kbd> then the file name..</p>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','repair_example','Repair Example','2008-11-24 14:25:44','');
INSERT INTO `language_text` VALUES ('en', '_template','replace_file','Replace File','2009-06-22 14:49:02','');
INSERT INTO `language_text` VALUES ('en', '_template','required_field','Required Field','2009-01-08 15:51:23','');
INSERT INTO `language_text` VALUES ('en', '_template','required_field_text','<div class=\"required\" title=\"Required Field\">*</div> indicates required fields.','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','requirement','Requirement','2008-11-24 14:25:44','');
INSERT INTO `language_text` VALUES ('en', '_template','reset_filter','Reset Filter','2008-11-27 09:48:36','');
INSERT INTO `language_text` VALUES ('en', '_template','result','Result','2008-12-01 14:45:48','');
INSERT INTO `language_text` VALUES ('en', '_template','results_found','Results Found: %s','2008-11-27 09:48:36','');
INSERT INTO `language_text` VALUES ('en', '_template','return_to_handbook','Return to Handbook','2009-01-28 15:28:06','');
INSERT INTO `language_text` VALUES ('en', '_template','save','Save','2009-01-15 10:01:07','');
INSERT INTO `language_text` VALUES ('en', '_template','save_and_close','Save and Close','2009-04-09 11:36:31','');
INSERT INTO `language_text` VALUES ('en', '_template','search','Search','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','search_phase','Search Phase','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','search_str','Search String','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','search_text','Search for terms that contains the given string. For example, search for phase \"desc\" returns all terms that contain string \"desc\".','2008-12-02 11:06:56','');
INSERT INTO `language_text` VALUES ('en', '_template','select','Select','2009-02-05 14:16:51','');
INSERT INTO `language_text` VALUES ('en', '_template','select_all','select/unselect all','2009-01-23 14:04:46','');
INSERT INTO `language_text` VALUES ('en', '_template','sent_via_transformable','Sent via an Transformable system at %s','2009-01-09 14:15:29','');
INSERT INTO `language_text` VALUES ('en', '_template','site_name','Site Name','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','sql_statement','SQL Statement','2009-06-22 14:49:02','');
INSERT INTO `language_text` VALUES ('en', '_template','status','Status','2009-01-21 12:38:52','');
INSERT INTO `language_text` VALUES ('en', '_template','submit','Submit','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','submit_no','No','2009-01-23 11:25:56','');
INSERT INTO `language_text` VALUES ('en', '_template','submit_yes','Yes','2009-01-23 11:25:56','');
INSERT INTO `language_text` VALUES ('en', '_template','system','System','2009-10-20 14:59:34','');
INSERT INTO `language_text` VALUES ('en', '_template','system_settings','System Settings','2009-10-21 10:48:59','');
INSERT INTO `language_text` VALUES ('en', '_template','system_update_id','System Update ID','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','term_type','Term Type','2009-03-24 13:47:37','');
INSERT INTO `language_text` VALUES ('en', '_template','theme','Theme','2009-10-21 15:19:36','');
INSERT INTO `language_text` VALUES ('en', '_template','the_follow_errors_occurred','The following errors occurred:','2008-12-15 09:25:06','');
INSERT INTO `language_text` VALUES ('en', '_template','title','Title','2009-01-20 11:45:23','');
INSERT INTO `language_text` VALUES ('en', '_template','translated_context','Translated Context','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','translated_terms','Translated Terms','2008-11-27 09:48:36','');
INSERT INTO `language_text` VALUES ('en', '_template','translated_text','Translated Text','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','translate_to','Translate to','2008-12-01 13:18:57','');
INSERT INTO `language_text` VALUES ('en', '_template','translation','Translation','2009-02-18 11:01:39','');
INSERT INTO `language_text` VALUES ('en', '_template','translator','Translator','2009-01-07 15:05:34','');
INSERT INTO `language_text` VALUES ('en', '_template','updated_terms','Updated Terms','2008-12-02 09:16:45','');
INSERT INTO `language_text` VALUES ('en', '_template','updater','Updater','2009-06-22 14:49:01','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','updater_alter_modified_files','The listed files have been modified locally. If you choose to proceed, your local file will be modified. The original\nfile will be backup before the modification. Please note that the modification on your customized code may break your customization.<br>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','updater_overwrite_modified_files','The listed files have been modified locally. If you choose to proceed, the update file will be copied to your local machine. \nYou have to manually merge this file and your local copy.<br>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','updater_show_backup_files','Below is the list of the backup files created by update installation. After ensuring Transformable works properly with the update, you may want to delete these files. If Transformable does not work properly with the update, you can always revert back to the old files by renaming the backup files \nto the original file names,  removing the [update_id].old portion of the file name. <br>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','updater_show_update_files','Below is the list of the update files copied to your computer. \nPlease manually merge the change between the update files and your local copy. <br>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','updates','Updates','2009-06-22 14:49:01','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','update_dependent_update_not_installed','<br /><span style=\"color: red\">Warning: There are update dependencies, please install the listed updates first: </span>','2009-06-22 14:49:03','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','update_local_file_not_exist','Cannot proceed. The listed files are not exist in your local machine. If you renamed them to your copy, in order to proceed, please rename back.<br>','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','upload','Upload','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','upload_file','Upload File','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','upload_update','Upload a zip file to install update:','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','user','User','2009-02-27 16:07:19','');
INSERT INTO `language_text` VALUES ('en', '_template','users','Users','2009-04-14 10:41:51','');
INSERT INTO `language_text` VALUES ('en', '_template','user_group','User Group','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','user_status','User Status','2009-02-04 11:51:16','');
INSERT INTO `language_text` VALUES ('en', '_template','use_captcha','Allow the use of CAPTCHA','2009-10-21 15:25:18','');
INSERT INTO `language_text` VALUES ('en', '_template','version_not_match','This update is for Transformable version %s. Does not match with your current Transformable version. The installation of it may break Transformable. Are you sure you want to proceed?','2009-06-22 14:49:02','Updater');
INSERT INTO `language_text` VALUES ('en', '_template','view','View','2009-01-20 11:47:15','');
INSERT INTO `language_text` VALUES ('en', '_template','view_message','View Message','2009-06-22 14:49:01','');
INSERT INTO `language_text` VALUES ('en', '_template','warning','Warning','2009-05-29 16:19:57','');
INSERT INTO `language_text` VALUES ('en', '_template','web_service_api','Web Service API','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','web_service_id','Web Service ID','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','web_site','Web Site','2009-02-06 09:08:32','');
INSERT INTO `language_text` VALUES ('en', '_template','welcome','Welcome','2009-10-07 09:55:16','');
INSERT INTO `language_text` VALUES ('en', '_template','yes','Yes','2009-01-21 12:38:17','');
INSERT INTO `language_text` VALUES ('en', '_template','yyyy-mm-dd','yyyy-mm-dd','2009-01-21 15:06:01','');
