<?php 
/************************************************************************/
/* AContent                                                        */
/************************************************************************/
/* Copyright (c) 2009                                                   */
/* Adaptive Technology Resource Centre / University of Toronto          */
/*                                                                      */
/* This program is free software. You can redistribute it and/or        */
/* modify it under the terms of the GNU General Public License          */
/* as published by the Free Software Foundation.                        */
/************************************************************************/
/* This file was generated by the AContent 1.2 installation script.     */
/* File generated 2012-10-16 11:10:40                                   */
/************************************************************************/
/************************************************************************/
/* the database user name                                               */
define('DB_USER',                      'root');

/* the database password                                                */
define('DB_PASSWORD',                  '');

/* the database host                                                    */
define('DB_HOST',                      'localhost');

/* the database tcp/ip port                                             */
define('DB_PORT',                      '3306');

/* the database name                                                    */
define('DB_NAME',                      'acontent');

/* The prefix to add to table names to avoid conflicts with existing    */
/* tables. Default: TR_                                                 */
define('TABLE_PREFIX',                 'AC_');

/* Where the content files are located.  This includes all file       */
/* manager and imported files.  If security is a concern, it is         */
/* recommended that the content directory be moved outside of the web	*/
/* accessible area.														*/
define('TR_CONTENT_DIR', 'C:\\xampp\\htdocs\\AContent\\content\\');

/* Whether or not to use the TR_CONTENT_DIR as a protected directory.   */
/* The if set to FALSE then the content directory will be hard coded    */
/* to Transformable_install_dir/content/ and TR_CONTENT_DIR will be ignored.   */
/* This option is used for compatability with IIS and Apache 2.         */
define('TR_FORCE_GET_FILE', TRUE);

/* DO NOT ALTER THIS LAST LINE                                          */
define('TR_INSTALL', TRUE);

?>